### ISSUE TITLE
Deadlock on full channel

### ISSUE THREAD

**Issue by thomersch** [vkorn/go-miio#1]
Hi vkorn,

Thanks for the library! I noticed that in long-running programs the library locks itself up. After some research, I realised that you have an `UpdateChan` in [vacuum.go:98](https://github.com/vkorn/go-miio/blob/master/vacuum.go#L98) that you fill up in [vacuum.go:207](https://github.com/vkorn/go-miio/blob/master/vacuum.go#L207). It is never read from, though.

I would have sent a pull request removing the channel, but I am not sure what the goal of the channel was. So maybe you can check it out and remove it if you don't intend to use it. If you wish, I can do this, too.

Best
Tom

**Comment by vkorn** [comment]
Hey, @thomersch 

This library is used as a part of another project, so some of the use cases might be different. 
Generally, those are internal vacuum updates which have to be collected from outside of the library, e.g. https://github.com/go-home-io/providers/blob/master/vacuum/xiaomi/vacuum.go#L154 where updateChan is https://github.com/go-home-io/providers/blob/master/vacuum/xiaomi/vacuum.go#L76

If you don't need those updates, I guess we can branch-out to a non-master and remove channel there.

**Comment by thomersch** [comment]
Ah, I see. This didn't become clear to me when I read the function definitions.

My software also has a timer that refreshes data from the vacuum, so I guess, I'll just restructure the flow, so I'll read from the channel.

Thanks again for the library!
